icons = "none"
theme = "plain"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 1800
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
bitrate = true
speed_up = false
speed_down = false
graph_up = false
graph_down = false
interval = 5

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
