" rc Includes
source ~/.vim/components/general.vim
source ~/.vim/components/plug.vim

" centralize vimfiles
set backupdir=$DOT_DIR/vim/backups
set directory=$DOT_DIR/vim/swaps
if exists("&undodir")
	set undodir=$DOT_DIR/vim/undo
endif

autocmd ColorScheme janah highlight Normal ctermbg=235
" colorscheme dracula
colorscheme janah
syntax enable

    " Disable tabs->spaces for Makefiles
autocmd FileType make setlocal noexpandtab
" Activate Goyo on Markdown
function! s:auto_goyo()
  if &ft == 'markdown'
    Goyo 80
  elseif exists('#goyo')
    let bufnr = bufnr('%')
    Goyo!
    execute 'b '.bufnr
  endif
endfunction

augroup goyo_markdown
  autocmd!
  autocmd BufNewFile,BufRead * call s:auto_goyo()
augroup END

autocmd FileType markdown setlocal spell

"" Plugin settings:
source ~/.vim/components/plugin_lightline.vim
source ~/.vim/components/plugin_various.vim

" DISTRACTION FREE MODE FOR VIM
" autocmd! User GoyoEnter Limelight
" autocmd! User GoyoLeave Limelight!

noremap <F12> :Goyo<CR>

let g:limelight_default_coefficient = 0.5
let g:limelight_paragraph_span = 1
let g:limelight_priority = -1
