" rc Includes
source ~/.vim/components/general.vim
source ~/.vim/components/plug.vim

" centralize vimfiles
set backupdir=$DOT_DIR/vim/backups
set directory=$DOT_DIR/vim/swaps
if exists("&undodir")
    set undodir=$DOT_DIR/vim/undo
endif

syntax enable
set background=dark
colorscheme gruvbox

if has("neovim-dot-app")
    set guifont=Iosevka Light:h13
end
if has("vimr")
    set guifont=Iosevka:h13
    set linespace=-1
    set guicursor+=a:blinkon0
end

" cursorlines
set cursorline
" set cursorcolumn
" hi CursorLine cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
" hi CursorLine cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
nnoremap <Leader>c :set cursorline!<CR>
" cursorcolumn!<CR>

set fillchars=fold:-,vert:\│

" share OSX clipboard
set clipboard=unnamed
" allow backspace in INSERT mode
set backspace=indent,eol,start
highlight Comment cterm=italic

source ~/.vim/components/autocmd.vim
source ~/.vim/components/line.vim
source ~/.vim/components/plugin-settings.vim
source ~/.vim/components/keys.vim
source ~/.vim/components/indent.vim
