" starting to use vim a little more

"" Plugin Manager
call plug#begin('~/.vim/plugged')
" >>> Plugin list:
" colorschemes
Plug 'zenorocha/dracula-theme', {'rtp': 'vim/'}
" interface
Plug 'nathanaelkane/vim-indent-guides'
Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'
" ux
Plug 'godlygeek/tabular'
Plug 'scrooloose/syntastic'
" lang specific
Plug 'fatih/vim-go', {'for': 'go'}
Plug 'gabrielelana/vim-markdown', {'for': 'markdown'}
" TDOD:
" c/cpp
" java
" python
" >>> End of Plugin List
call plug#end()

" centralize vimfiles
set backupdir=$DOT_DIR/vim/backups
set directory=$DOT_DIR/vim/swaps
if exists("&undodir")
	set undodir=$DOT_DIR/vim/undo
endif

" solarized options:
"let g:solarized_termcolors=256
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
"colorscheme solarized

set encoding=utf-8 nobomb
set nocompatible
syntax enable

"" General settings
set number
set linebreak
set showbreak=+++ 
set textwidth=100
set showmatch
set visualbell

set hlsearch
set smartcase
set ignorecase
set incsearch

set autoindent
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
set expandtab

" always show status line
set laststatus=2
set noerrorbells
set showmode
set showcmd

" allow backspace in INSERT mode
set backspace=indent,eol,start

if has("gui_vimr")
    " Vimr specific stuff
    colorscheme dracula
    set guifont=Iosevka:h12
endif

"" Plugin settings:

" vim-go
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_autosave = 1

let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
