#!/usr/bin/env zsh

# === ZSH ENV
# sourced for every shell
# exception: use '-f'
#

export DOT_DIR=$HOME/.dotfiles

export ZDOTDIR=$DOT_DIR/zsh
export ZSHDIR=$HOME/.zsh
export ZPLUG_HOME=$ZDOTDIR/.zplug

export XDG_CONFIG_HOME="$HOME/.config"
export PATH=$HOME/bin:$PATH
# export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
